In [ ]:
pip install pandas

Defaulting to user installation because normal site-packages is not writeable
Requirement already satisfied: pandas in c:\users\rajva\appdata\roaming\python\python313\site-packages (3.0.2)
Requirement already satisfied: numpy>=1.26.0 in c:\users\rajva\appdata\roaming\python\python313\site-packages (from pandas) (2.4.4)
Requirement already satisfied: python-dateutil>=2.8.2 in c:\users\rajva\appdata\roaming\python\python313\site-packages (from pandas) (2.9.0.post0)
Requirement already satisfied: tzdata in c:\users\rajva\appdata\roaming\python\python313\site-packages (from pandas) (2026.1)
Requirement already satisfied: six>=1.5 in c:\users\rajva\appdata\roaming\python\python313\site-packages (from python-dateutil>=2.8.2->pandas) (1.17.0)
Note: you may need to restart the kernel to use updated packages.

[notice] A new release of pip is available: 25.0.1 -> 26.1
[notice] To update, run: python.exe -m pip install --upgrade pip

In [ ]:
import pandas as pd

In [ ]:
df = pd.read_csv(r"1_student dataset.csv")

In [ ]:
print(df)

     gender race/ethnicity parental level of education         lunch  \
0    female        group B           bachelor's degree      standard
1    female        group C                some college      standard
2    female        group B             master's degree      standard
3      male        group A          associate's degree  free/reduced
4      male        group C                some college      standard
..      ...            ...                         ...           ...
995  female        group E             master's degree      standard
996    male        group C                 high school  free/reduced
997  female        group C                 high school  free/reduced
998  female        group D                some college      standard
999  female        group D                some college  free/reduced

    test preparation course  math score  reading score  writing score
0                      none          72             72            NaN
1                 completed          69             90           88.0
2                      none          90             95           93.0
3                      none          47             57           44.0
4                      none          76             78           75.0
..                      ...         ...            ...            ...
995               completed          88             99           95.0
996                    none          62             55           55.0
997               completed          59             71           65.0
998               completed          68             78           77.0
999                    none          77             86           86.0

[1000 rows x 8 columns]

In [ ]:
df.head(10)

,gender,race/ethnicity,parental level of education,lunch,test preparation course,math score,reading score,writing score
0,female,group B,bachelor's degree,standard,none,72,72,NaN
1,female,group C,some college,standard,completed,69,90,88.0
2,female,group B,master's degree,standard,none,90,95,93.0
3,male,group A,associate's degree,free/reduced,none,47,57,44.0
4,male,group C,some college,standard,none,76,78,75.0
5,female,group B,associate's degree,standard,none,71,83,78.0
6,female,group B,some college,standard,completed,88,95,92.0
7,male,group B,some college,free/reduced,none,40,43,39.0
8,male,group D,high school,free/reduced,completed,64,64,67.0
9,female,group B,high school,free/reduced,none,38,60,50.0

In [ ]:
df.isnull().sum()

gender                         0
race/ethnicity                 0
parental level of education    0
lunch                          0
test preparation course        0
math score                     0
reading score                  0
writing score                  1
dtype: int64

In [ ]:
print(df.describe())

       math score  reading score  writing score
count  1000.00000    1000.000000     999.000000
mean     66.08900      69.169000      68.048048
std      15.16308      14.600192      15.202102
min       0.00000      17.000000      10.000000
25%      57.00000      59.000000      57.500000
50%      66.00000      70.000000      69.000000
75%      77.00000      79.000000      79.000000
max     100.00000     100.000000     100.000000

In [ ]:
df.dtypes

gender                             str
race/ethnicity                     str
parental level of education        str
lunch                              str
test preparation course            str
math score                       int64
reading score                    int64
writing score                  float64
dtype: object

In [ ]:
df.dropna(axis=1)

,gender,race/ethnicity,parental level of education,lunch,test preparation course,math score,reading score
0,female,group B,bachelor's degree,standard,none,72,72
1,female,group C,some college,standard,completed,69,90
2,female,group B,master's degree,standard,none,90,95
3,male,group A,associate's degree,free/reduced,none,47,57
4,male,group C,some college,standard,none,76,78
...,...,...,...,...,...,...,...
995,female,group E,master's degree,standard,completed,88,99
996,male,group C,high school,free/reduced,none,62,55
997,female,group C,high school,free/reduced,completed,59,71
998,female,group D,some college,standard,completed,68,78
999,female,group D,some college,free/reduced,none,77,86

In [ ]:
y = df.iloc[:, 0:1]
print(y)

     gender
0    female
1    female
2    female
3      male
4      male
..      ...
995  female
996    male
997  female
998  female
999  female

[1000 rows x 1 columns]

In [ ]:
from sklearn.preprocessing import LabelEncoder
le = LabelEncoder()
y = le.fit_transform(y)
print(y)

C:\Users\rajva\AppData\Roaming\Python\Python313\site-packages\sklearn\preprocessing\_label.py:120: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples, ), for example using ravel().
  y = column_or_1d(y, warn=True)

[0 0 0 1 1 0 0 1 1 0 1 1 0 1 0 0 1 0 1 0 1 0 1 0 1 1 1 0 1 0 0 0 0 1 1 1 0
 0 0 1 1 0 0 1 0 1 0 0 0 1 1 1 1 1 0 0 0 1 1 0 1 1 1 0 0 1 1 0 1 0 0 1 0 1
 1 1 1 1 0 0 0 1 1 1 1 0 0 0 0 0 0 1 1 1 0 1 1 0 0 0 1 1 0 1 1 0 0 1 0 0 0
 1 1 0 0 1 0 0 0 0 0 1 0 1 1 0 1 1 1 0 1 1 1 0 1 1 1 1 0 1 0 0 0 1 1 0 1 1
 0 1 1 1 0 1 1 0 0 1 0 1 1 0 1 1 0 0 1 0 0 0 1 1 0 0 0 0 0 0 0 0 1 0 0 0 1
 1 1 1 1 0 0 1 0 1 0 1 1 1 0 0 0 0 1 0 1 1 1 1 0 0 1 1 0 1 1 1 0 0 1 1 0 1
 0 1 0 0 0 1 1 0 1 1 0 1 1 1 1 0 1 1 1 0 0 1 1 1 1 0 0 1 1 0 0 1 1 0 0 1 0
 0 0 1 0 0 1 1 0 0 0 0 1 1 0 0 1 1 0 0 0 1 1 1 0 0 0 1 1 0 1 1 1 1 1 0 1 1
 1 1 1 1 1 1 0 1 0 1 1 1 0 0 0 1 1 0 0 1 0 1 1 0 0 0 0 0 0 0 1 1 1 0 1 1 1
 1 0 0 1 1 0 0 1 0 0 1 1 0 1 0 1 1 0 1 0 0 0 0 1 0 1 0 0 1 0 0 1 1 1 1 0 0
 1 0 1 0 0 1 0 0 0 1 0 1 1 0 0 0 0 0 0 1 1 0 1 1 0 1 0 0 1 1 0 1 0 0 0 0 1
 0 0 1 0 1 1 1 0 1 1 1 1 1 0 0 0 0 1 0 1 1 1 1 1 0 1 0 1 1 1 1 1 1 0 0 0 0
 1 0 1 1 1 1 0 0 0 1 0 1 0 1 0 1 1 1 0 0 1 0 0 1 0 1 0 0 0 0 0 0 1 1 0 1 1
 0 1 1 0 1 1 0 1 1 0 0 0 0 0 1 0 0 0 1 0 0 1 0 0 0 1 1 1 0 1 1 1 0 0 0 0 0
 0 0 1 0 1 1 1 1 1 0 0 0 0 0 1 0 1 0 1 0 1 1 1 1 0 0 0 1 0 1 0 1 1 1 0 1 1
 0 0 1 0 1 0 0 1 0 1 1 0 0 1 1 1 1 0 0 0 1 1 0 0 0 0 0 0 0 0 0 0 0 0 0 1 1
 1 0 0 0 1 1 0 0 0 0 0 1 1 1 0 0 0 0 1 0 1 0 0 0 0 1 1 1 0 1 1 1 0 1 1 1 1
 0 1 1 0 0 1 1 0 0 1 0 1 0 0 0 1 0 0 0 0 0 1 0 0 0 0 0 1 1 0 1 1 1 0 0 1 0
 0 0 1 1 0 1 0 0 0 0 0 0 1 1 0 1 1 0 1 0 1 1 1 1 0 0 0 0 0 0 0 0 0 1 0 0 1
 0 0 1 1 1 1 0 1 0 0 1 0 0 1 0 0 1 0 1 0 1 1 1 0 1 0 1 0 1 0 1 0 1 1 0 1 1
 1 0 0 0 1 1 1 1 0 1 1 1 1 0 1 0 1 1 0 1 0 0 1 0 1 0 0 1 0 1 1 1 0 0 1 0 0
 0 0 1 0 0 0 0 1 0 0 0 1 0 0 0 1 1 0 0 1 0 1 0 1 1 0 0 0 1 0 0 1 1 1 1 0 1
 0 1 0 1 0 0 0 0 1 0 0 1 0 0 0 1 0 0 1 0 1 0 1 0 1 0 0 1 0 1 0 1 1 1 0 1 1
 0 0 1 1 0 1 0 1 1 0 0 1 0 1 1 1 1 1 1 1 0 1 1 0 1 1 1 0 0 1 0 0 1 0 0 0 1
 0 1 0 0 0 1 0 0 1 0 1 0 1 0 0 0 0 1 1 0 0 1 1 0 0 0 0 0 1 0 0 1 1 0 1 0 1
 1 1 0 1 0 1 1 1 1 1 1 1 0 1 1 1 0 1 1 0 0 1 0 1 0 1 0 0 1 0 1 1 0 0 1 0 0
 0 0 1 0 1 1 0 0 0 1 0 0 0 0 1 1 1 0 0 1 1 0 0 1 0 1 0 0 1 0 0 0 1 0 1 0 0
 0]

In [ ]:
print(df['race/ethnicity'].value_counts())

race/ethnicity
group C    319
group D    262
group B    190
group E    140
group A     89
Name: count, dtype: int64

In [ ]:
df_Lunch = pd.get_dummies(df['lunch'])
df_new = pd.concat([df, df_Lunch], axis=1)
print(df_new)

     gender race/ethnicity parental level of education         lunch  \
0    female        group B           bachelor's degree      standard
1    female        group C                some college      standard
2    female        group B             master's degree      standard
3      male        group A          associate's degree  free/reduced
4      male        group C                some college      standard
..      ...            ...                         ...           ...
995  female        group E             master's degree      standard
996    male        group C                 high school  free/reduced
997  female        group C                 high school  free/reduced
998  female        group D                some college      standard
999  female        group D                some college  free/reduced

    test preparation course  math score  reading score  writing score  \
0                      none          72             72            NaN
1                 completed          69             90           88.0
2                      none          90             95           93.0
3                      none          47             57           44.0
4                      none          76             78           75.0
..                      ...         ...            ...            ...
995               completed          88             99           95.0
996                    none          62             55           55.0
997               completed          59             71           65.0
998               completed          68             78           77.0
999                    none          77             86           86.0

     free/reduced  standard
0           False      True
1           False      True
2           False      True
3            True     False
4           False      True
..            ...       ...
995         False      True
996          True     False
997          True     False
998         False      True
999          True     False

[1000 rows x 10 columns]

In [ ]:
from sklearn.preprocessing import MinMaxScaler

scaler = MinMaxScaler()

# Apply normalization to numeric columns
df[['math score', 'reading score', 'writing score']] = scaler.fit_transform(
    df[['math score', 'reading score', 'writing score']]
)

print(df.head())

   gender race/ethnicity parental level of education         lunch  \
0  female        group B           bachelor's degree      standard
1  female        group C                some college      standard
2  female        group B             master's degree      standard
3    male        group A          associate's degree  free/reduced
4    male        group C                some college      standard

  test preparation course  math score  reading score  writing score
0                    none        0.72       0.662651            NaN
1               completed        0.69       0.879518       0.866667
2                    none        0.90       0.939759       0.922222
3                    none        0.47       0.481928       0.377778
4                    none        0.76       0.734940       0.722222

pip install pandas

EXPLANATION :

pip is a command-line tool in Python known as Python Package Installer.
It is used to download and install external libraries that are not available in Python by default.

Python alone has limited functionality for handling large datasets.
Therefore, we install external libraries like pandas to extend its capabilities.

install is a command given to pip which tells it to install a package.

pandas is the name of the library we want to install.
It is used for data manipulation, data analysis, and preprocessing.

Internally, when this command is executed, pip connects to an online repository called Python Package Index (PyPI).
It searches for the pandas package.
It downloads the required files.
It installs them into the Python environment so they can be imported later.

import pandas as pd

EXPLANATION :

import is a Python keyword used to include a library into the program.

pandas is the library name that contains functions for handling structured data.

as is a keyword used to create an alias (a short name).

pd is the alias assigned to pandas.

This is done to reduce typing and improve readability.

Instead of writing pandas.read_csv(), we write pd.read_csv().

Internally, Python loads the pandas module into memory and maps it to the name pd.

df = pd.read_csv("StudentsPerformance.csv")

EXPLANATION :

df is a variable name used to store the dataset.
It stands for DataFrame.

= is the assignment operator used to store the result of the right-hand side into the left-hand side variable.

pd is the alias of pandas.

. is the dot operator used to access functions from a library.

read_csv() is a function used to read data from a CSV file.

"StudentsPerformance.csv" is a string representing the file name.

Internally, read_csv() performs the following steps:
It opens the file from the given location.
It reads the file line by line.
It splits each line based on commas.
It identifies the first row as column names.
It converts the remaining rows into structured data.
It stores everything in a DataFrame object.

The final DataFrame is stored in df.

print(df)

EXPLANATION :

print() is a built-in Python function used to display output.

df is the DataFrame containing the dataset.

When this statement is executed, Python sends the DataFrame to the output console.

Internally, pandas formats the data into rows and columns and displays it in a readable tabular format.

This helps the user to visually inspect the data.

df.head(10)

EXPLANATION :

df is the DataFrame.

. is used to access a function.

head() is a pandas function that returns the first few rows of the dataset.

10 is the argument specifying how many rows to display.

Internally, pandas selects rows starting from index 0 up to index 9.

It extracts these rows and returns them as a new DataFrame.

This is useful for quickly understanding the structure of the data without printing the entire dataset.

df.isnull().sum()

EXPLANATION :

df is the DataFrame.

isnull() is a function that checks for missing values in the dataset.

Internally, isnull() goes through each cell of the DataFrame.
If a value is missing (NaN), it returns True.
If a value is present, it returns False.

This produces a new DataFrame of the same shape containing True and False values.

. is used to chain another function.

sum() is applied to the result of isnull().

Internally, sum() treats True as 1 and False as 0.
It adds values column-wise by default.

So it counts the number of missing values in each column.

df.describe()

EXPLANATION :

df is the DataFrame.

. accesses the function.

describe() is a pandas function that provides statistical summary of numerical columns.

Internally, describe() performs multiple operations:

It counts non-null values in each column.

It calculates mean using the formula:
mean = sum of all values divided by number of values

It calculates standard deviation which measures how far values are spread from the mean.

It finds the minimum value.

It calculates percentiles:
25% (first quartile)
50% (median)
75% (third quartile)

It finds the maximum value.

The result is returned as a new DataFrame containing all these statistics.

df.dtypes

EXPLANATION :

df is the DataFrame.

. is used to access an attribute.

dtypes is an attribute that shows the datatype of each column.

It does not use parentheses because it is not a function.

Internally, pandas checks each column and determines its datatype such as:
int64 for integers
float64 for decimal numbers
object for strings

This helps identify which columns are numeric and which are categorical.

df.dropna(axis=1)

EXPLANATION :

df is the DataFrame.

dropna() is a function used to remove missing values.

axis=1 specifies the direction of operation.

axis=0 means rows.
axis=1 means columns.

So axis=1 means remove columns that contain missing values.

Internally, pandas scans each column.
If any missing value is found in a column, that column is removed.

This function returns a new DataFrame and does not modify the original unless assigned.

y = df.iloc[:, 0:1]

EXPLANATION :

y is a variable used to store selected data.

= assigns the result.

df is the DataFrame.

iloc stands for integer location.
It is used for index-based selection.

: means select all rows.

, separates row selection and column selection.

0:1 means select columns from index 0 up to but not including index 1.

So only the first column is selected.

Internally, pandas accesses data using index positions and extracts the required portion.

from sklearn.preprocessing import LabelEncoder

EXPLANATION :

from is used to import a specific part of a module.

sklearn is a machine learning library.

preprocessing is a module used for data preparation.

import is used to bring the class into the program.

LabelEncoder is a class used to convert categorical text into numeric values.

Internally, Python loads only the required class instead of the entire library.

le = LabelEncoder()

EXPLANATION :

le is a variable that stores the encoder object.

= assigns the object.

LabelEncoder() creates an instance of the LabelEncoder class.

Internally, memory is allocated and an object is created that can learn categories and perform encoding.

y = le.fit_transform(y)

EXPLANATION :

le is the LabelEncoder object.

. accesses its method.

fit_transform() is a combination of two operations:

fit() scans the data and identifies all unique categories.

For example, it finds values like "male" and "female".

transform() assigns numbers to these categories.

For example:
female → 0
male → 1

Internally, it creates a mapping table and replaces values accordingly.

The transformed numeric data is stored back into y.

df['race/ethnicity'].value_counts()

EXPLANATION :

df is the DataFrame.

['race/ethnicity'] selects a specific column by name.

. accesses the function.

value_counts() counts occurrences of each unique value.

Internally, pandas scans the column.
It identifies unique categories.
It counts how many times each category appears.

The result is returned as a series.

df_Lunch = pd.get_dummies(df['lunch'])

EXPLANATION :

df_Lunch is a variable storing the encoded data.

= assigns the result.

pd is pandas.

get_dummies() is a function used for one-hot encoding.

df['lunch'] selects the lunch column.

Internally, pandas identifies all unique categories.

For each category, it creates a new column.

Each row is assigned 1 if it belongs to that category, otherwise 0.

This avoids assigning order between categories.

df_new = pd.concat([df, df_Lunch], axis=1)

EXPLANATION :

df_new is a variable storing the combined dataset.

= assigns the result.

pd.concat() is a function used to combine DataFrames.

[df, df_Lunch] is a list of DataFrames to combine.

axis=1 means combine column-wise.

Internally, pandas aligns rows using index and joins columns side by side.

The result is a new DataFrame containing both original and encoded columns.

WHAT WE ARE ACTUALLY DOING IN THIS CODE :

In this code, we are taking raw data from a CSV file and preparing it for machine learning.

First, we load the data into a structured format using pandas.

Then, we inspect the data to understand its structure.

Next, we check for missing values and identify incomplete data.

We analyze the dataset using statistical functions to understand distribution.

We check datatypes to know which data is numeric and which is categorical.

We clean the data by removing missing values.

We select specific columns for processing.

We convert categorical text data into numerical form using Label Encoding.

We also use One Hot Encoding to avoid incorrect ordering of categories.

Finally, we combine all processed data into one dataset.

The final goal is to convert raw, messy data into a clean, numerical format that can be used for machine learning algorithms.