In [4]:
import numpy as np
import matplotlib.pyplot as plt
%matplotlib inline

In [5]:
import pandas as pd

In [6]:
df = pd.read_csv(r"AcademicPerformance.csv")

In [7]:
print(df)

      gender race/ethnicity parental level of education         lunch  \
0     female        group B           bachelor's degree      standard
1     female        group C                some college      standard
2     female        group B             master's degree      standard
3       male        group A          associate's degree  free/reduced
4       male        group C                some college      standard
...      ...            ...                         ...           ...
2235     NaN            NaN                         NaN           NaN
2236     NaN            NaN                         NaN           NaN
2237     NaN            NaN                         NaN           NaN
2238     NaN            NaN                         NaN           NaN
2239     NaN            NaN                         NaN           NaN

     test preparation course  Year_Birth  math score reading score  \
0                       none      1970.0        72.0            72
1                  completed      1961.0         NaN            na
2                       none      1958.0        90.0            95
3                       none      1967.0         NaN           NaN
4                       none      1989.0        76.0            78
...                      ...         ...         ...           ...
2235                     NaN         NaN         NaN           NaN
2236                     NaN         NaN         NaN           NaN
2237                     NaN         NaN         NaN           NaN
2238                     NaN         NaN         NaN           NaN
2239                     NaN         NaN         NaN           NaN

     writing score Dt_Admission College_Fees
0               74      6/16/14  $84,835.00
1                A      6/15/14  $57,091.00
2               93      5/13/14  $67,267.00
3               44   05-11-2014  $32,474.00
4               75   04-08-2014  $21,474.00
...            ...          ...          ...
2235           NaN          NaN          NaN
2236           NaN          NaN          NaN
2237           NaN          NaN          NaN
2238           NaN          NaN          NaN
2239           NaN          NaN          NaN

[2240 rows x 11 columns]

In [8]:
print(df['math score'])

0       72.0
1        NaN
2       90.0
3        NaN
4       76.0
        ...
2235     NaN
2236     NaN
2237     NaN
2238     NaN
2239     NaN
Name: math score, Length: 2240, dtype: float64

In [9]:
print(df['math score'].isnull())

0       False
1        True
2       False
3        True
4       False
        ...
2235     True
2236     True
2237     True
2238     True
2239     True
Name: math score, Length: 2240, dtype: bool

In [10]:
print(df['reading score'])

0        72
1        na
2        95
3       NaN
4        78
       ...
2235    NaN
2236    NaN
2237    NaN
2238    NaN
2239    NaN
Name: reading score, Length: 2240, dtype: object

In [11]:
print(df['reading score'].isnull())

0       False
1       False
2       False
3        True
4       False
        ...
2235     True
2236     True
2237     True
2238     True
2239     True
Name: reading score, Length: 2240, dtype: bool

In [13]:
missing_values = ["n/a", "na", "--"]
df = pd.read_csv(r"AcademicPerformance.csv", na_values = missing_values)

In [ ]:
print(df['reading score'])

0       72.0
1        NaN
2       95.0
3        NaN
4       78.0
        ...
2235     NaN
2236     NaN
2237     NaN
2238     NaN
2239     NaN
Name: reading score, Length: 2240, dtype: float64

In [ ]:
print(df['reading score'].isnull())

0       False
1        True
2       False
3        True
4       False
        ...
2235     True
2236     True
2237     True
2238     True
2239     True
Name: reading score, Length: 2240, dtype: bool

In [ ]:
dataset = [11,41,20,3,101,55,68,97,99,6]

In [ ]:
sorted(dataset)

[3, 6, 11, 20, 41, 55, 68, 97, 99, 101]

In [ ]:
quantile1, quantile3 = np.percentile(dataset, [25,75])

In [ ]:
print(quantile1, quantile3)

13.25 89.75

In [ ]:
iqr_value = (quantile3 - quantile1)

In [ ]:
print(iqr_value)

76.5

In [ ]:
lower_bound_value = quantile1 - (1.5*iqr_value)

In [ ]:
upper_bound_value = quantile3 + (1.5*iqr_value)

In [ ]:
print(lower_bound_value, upper_bound_value)

-101.5 204.5

In [ ]:
from datetime import date
df['age'] = date.today().year - df['Year_Birth']

In [ ]:
df['Year'] = pd.DatetimeIndex(df['Dt_Admission']).year
df['E_L'] = date.today().year - df['Year']

In [ ]:
df.head(5)

,gender,race/ethnicity,parental level of education,lunch,test preparation course,Year_Birth,math score,reading score,writing score,Dt_Admission,College_Fees,age,Year,E_L
0,female,group B,bachelor's degree,standard,none,1970.0,72.0,72.0,74,6/16/14,"$84,835.00",52.0,2014.0,8.0
1,female,group C,some college,standard,completed,1961.0,NaN,NaN,A,6/15/14,"$57,091.00",61.0,2014.0,8.0
2,female,group B,master's degree,standard,none,1958.0,90.0,95.0,93,5/13/14,"$67,267.00",64.0,2014.0,8.0
3,male,group A,associate's degree,free/reduced,none,1967.0,NaN,NaN,44,05-11-2014,"$32,474.00",55.0,2014.0,8.0
4,male,group C,some college,standard,none,1989.0,76.0,78.0,75,04-08-2014,"$21,474.00",33.0,2014.0,8.0

In [ ]:
df['Fees$'] = df['College_Fees'].str.replace(',', '').str.replace('$', '').str.replace('.', '').fillna(0).astype(int)
df['Fees_M$'] = df['Fees$'].apply(lambda X:round(X/1000000))

In [ ]:
df.head(5)

,gender,race/ethnicity,parental level of education,lunch,test preparation course,Year_Birth,math score,reading score,writing score,Dt_Admission,College_Fees,age,Year,E_L,Fees$,Fees_M$
0,female,group B,bachelor's degree,standard,none,1970.0,72.0,72.0,74,6/16/14,"$84,835.00",52.0,2014.0,8.0,8483500,8
1,female,group C,some college,standard,completed,1961.0,NaN,NaN,A,6/15/14,"$57,091.00",61.0,2014.0,8.0,5709100,6
2,female,group B,master's degree,standard,none,1958.0,90.0,95.0,93,5/13/14,"$67,267.00",64.0,2014.0,8.0,6726700,7
3,male,group A,associate's degree,free/reduced,none,1967.0,NaN,NaN,44,05-11-2014,"$32,474.00",55.0,2014.0,8.0,3247400,3
4,male,group C,some college,standard,none,1989.0,76.0,78.0,75,04-08-2014,"$21,474.00",33.0,2014.0,8.0,2147400,2

BLOCK 1
import numpy as npimport matplotlib.pyplot as plt%matplotlib inline
EXPLANATION :
import
This is a Python keyword used to include external libraries into the current program.
Without using import, Python cannot recognize functions that belong to that library.
It is necessary because Python does not load all libraries by default to save memory.
numpy
This is a library specially designed for numerical computations.
It provides support for arrays, matrices, mathematical functions, and statistical operations.
It is used because normal Python lists are slower and do not support vectorized operations.
as
This keyword is used to assign an alias (short name) to the imported library.
This improves code readability and reduces typing effort.
np
This is the alias given to numpy.
Instead of writing numpy.percentile(), we write np.percentile() which is shorter and cleaner.
import matplotlib.pyplot as plt
This line imports the pyplot module from the matplotlib library.
matplotlib is a plotting library used for creating graphs and visualizations.
pyplot contains functions like plot(), bar(), hist() etc.
plt
This is the alias for matplotlib.pyplot.
It allows us to call plotting functions using a short name.
%matplotlib inline
This is a Jupyter Notebook magic command.
It ensures that any graph created using matplotlib is displayed inside the notebook.
Without this, graphs may open in a separate window or may not display properly.
What we are doing in this block
We are preparing the environment by importing libraries required for numerical analysis and visualization.

 BLOCK 2
import pandas as pd
EXPLANATION :
pandas
This is a Python library used for data manipulation and analysis.
It is specifically designed to work with structured data like tables.
import pandas
This loads the pandas library into memory so we can use its functions.
as
Used to create an alias for easier usage.
pd
Alias for pandas.
Instead of writing pandas.read_csv(), we use pd.read_csv().
Internal working of pandas
Pandas provides a data structure called DataFrame.
A DataFrame is a 2-dimensional structure with rows and columns similar to an Excel sheet.
It allows operations like filtering, sorting, grouping, aggregation, and cleaning.
What we are doing in this block
We are importing pandas to handle tabular data efficiently.

 BLOCK 3
df = pd.read_csv("AcademicPerformance.csv")
EXPLANATION :
df
This is a variable name used to store the dataset.
It stands for DataFrame.
=
Assignment operator used to store the result of the right-hand side into the left-hand variable.
pd.read_csv()
This is a pandas function used to read a CSV file.
"AcademicPerformance.csv"
This is a string representing the file name.
The file must be present in the working directory.
Internal working of read_csv()
Step 1: Opens the file in read mode
Step 2: Reads the first row as column headers
Step 3: Reads each subsequent row
Step 4: Splits values using comma delimiter
Step 5: Converts each row into structured format
Step 6: Stores everything into a DataFrame
Step 7: Automatically detects data types if possible
What we are doing in this block
We are loading the dataset into a DataFrame so we can perform operations on it.

 BLOCK 4
print(df)
EXPLANATION :
print()
This is a built-in Python function used to display output.
df
The DataFrame containing our dataset.
Internal working
The DataFrame is converted into a string representation
Rows and columns are formatted neatly
Then displayed on the screen
What we are doing
We are viewing the entire dataset to understand its structure.

 BLOCK 5
print(df['math score'])
EXPLANATION :
df['math score']
This is used to access a specific column from the DataFrame.
'math score'
This is the column name and must match exactly with the dataset.
Internal working
The DataFrame searches for a column named "math score"
It extracts that column
Returns it as a Series (single column structure)
print()
Displays the extracted column
What we are doing
We are selecting only the math score column for focused analysis.

 BLOCK 6
print(df['math score'].isnull())
EXPLANATION :
.isnull()
This is a pandas function used to detect missing values.
Internal working step-by-step
Step 1: Iterates through each value in the column
Step 2: Checks if the value is NaN or empty
Step 3: Returns True if missing
Step 4: Returns False if present
Output
A Boolean Series containing True and False values.
What we are doing
We are identifying missing values in the dataset.

 BLOCK 7
missing_values = ["n/a", "na", "--"]df = pd.read_csv("AcademicPerformance.csv", na_values=missing_values)
EXPLANATION :
missing_values
Variable storing a list.
["n/a", "na", "--"]
These are string values that represent missing data in many datasets.
na_values=missing_values
Parameter in read_csv that tells pandas to treat these values as missing.
Internal working
While reading the file
Each value is checked
If it matches "n/a", "na", or "--"
It is replaced with NaN (Not a Number)
What we are doing
We are standardizing missing values so that pandas can properly recognize them.

 BLOCK 8
dataset = [11,41,20,3,101,55,68,97,99,6]
EXPLANATION :
dataset
Variable storing a list.
[]
Denotes a list in Python.
Values inside list
These are integers separated by commas.
Internal working
Python stores these values in memory sequentially
Each element has an index starting from 0
What we are doing
We are creating a sample dataset for statistical calculations.

 BLOCK 9
sorted(dataset)
EXPLANATION :
sorted()
A built-in Python function used to sort data.
Internal working
Step 1: Takes the list as input
Step 2: Uses Timsort algorithm (hybrid sorting algorithm)
Step 3: Compares elements
Step 4: Arranges them in ascending order
Step 5: Returns a new sorted list
Important point
Original dataset remains unchanged.
What we are doing
We are organizing data to prepare for statistical analysis.

 BLOCK 10
quantile1, quantile3 = np.percentile(dataset, [25,75])
EXPLANATION :
np.percentile()
Function used to compute percentiles.
dataset
Input data.
[25,75]
We are requesting 25th percentile (Q1) and 75th percentile (Q3).
Formula for percentile position
Position = (P/100) × (N-1)
Where P = percentile, N = number of values
Internal working
Step 1: Sort the dataset
Step 2: Calculate index using formula
Step 3: If index is fractional, perform interpolation
Step 4: Return corresponding values
quantile1
Stores Q1 value
quantile3
Stores Q3 value
What we are doing
We are dividing the dataset into parts to understand its distribution.

 BLOCK 11
iqr_value = (quantile3 - quantile1)
EXPLANATION :
iqr_value
Variable storing result.
quantile3 - quantile1
Subtraction operation.
Formula
IQR = Q3 - Q1
Meaning
Represents spread of middle 50% of data.
What we are doing
We are measuring variability of data.

 BLOCK 12
lower_bound_value = quantile1 - (1.5*iqr_value)upper_bound_value = quantile3 + (1.5*iqr_value)
EXPLANATION :
1.5*iqr_value
Multiplier used in outlier detection.
Formulas
Lower Bound = Q1 − 1.5 × IQR
Upper Bound = Q3 + 1.5 × IQR
Internal logic
Values outside this range are considered outliers
This rule comes from boxplot statistical method
What we are doing
We are identifying abnormal values in the dataset.

 BLOCK 13
from datetime import datedf['age'] = date.today().year - df['Year_Birth']
EXPLANATION :
from datetime import date
Imports the date class from datetime module.
date.today()
Returns current date.
.year
Extracts current year.
df['Year_Birth']
Column containing birth year.
Formula
Age = Current Year − Birth Year
What we are doing
We are calculating age for each record.

 BLOCK 14
df['Year'] = pd.DatetimeIndex(df['Dt_Admission']).year
EXPLANATION :
pd.DatetimeIndex()
Converts column into datetime format.
.year
Extracts year component.
Internal working
Step 1: Parses string date
Step 2: Converts into datetime object
Step 3: Extracts year
What we are doing
We are extracting admission year.

 BLOCK 15
df['E_L'] = date.today().year - df['Year']
EXPLANATION :
E_L
New column name.
Formula
Experience = Current Year − Admission Year
What we are doing
We are calculating experience in years.

 BLOCK 16
df.head(5)
EXPLANATION :
head()
Pandas function used to display top rows.
5
Number of rows to display.
Internal working
Returns first 5 rows without modifying original dataset.
What we are doing
We are previewing the dataset.

 BLOCK 17
df['Fees$'] = df['College_Fees'].str.replace(',', '').str.replace('$', '').str.replace('.', '').fillna(0).astype(int)
EXPLANATION :
.str.replace()
Used to replace characters in string.
Removes
Comma, dollar sign, dot
.fillna(0)
Replaces missing values with 0
.astype(int)
Converts data type to integer
Internal working
Step 1: Remove unwanted characters
Step 2: Handle missing values
Step 3: Convert to numeric format
What we are doing
We are cleaning and converting fee data into usable numeric format.

BLOCK 18
df['Fees_M$'] = df['Fees$'].apply(lambda X: round(X/1000000))
EXPLANATION :
.apply()
Applies a function to each element.
lambda
Anonymous function.
X
Represents each value in column.
X/1000000
Converts value to millions.
round()
Rounds the value.
Internal working
Step 1: Takes each value
Step 2: Applies lambda function
Step 3: Stores result
What we are doing
We are converting fees into millions for easier understanding.

WHAT WE ARE ACTUALLY DOING IN THIS CODE
We are performing data preprocessing and analysis.
Step-by-step
We import libraries
We load dataset
We explore data
We handle missing values
We perform statistical calculations
We detect outliers using IQR formula
We transform data (age, experience)
We clean messy data
We convert data into useful format
Final purpose
To convert raw data into clean, structured, and analyzable form for further analysis or machine learning.